/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LecturaSlugRouteImport } from './routes/lectura.$slug'
import { Route as TestSlugRouteImport } from './routes/test.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturaSlugRoute = LecturaSlugRouteImport.update({
  id: '/lectura/$slug',
  path: '/lectura/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSlugRoute = TestSlugRouteImport.update({
  id: '/test/$slug',
  path: '/test/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/perfil': typeof PerfilRoute
  '/lectura/$slug': typeof LecturaSlugRoute
  '/test/$slug': typeof TestSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/perfil': typeof PerfilRoute
  '/lectura/$slug': typeof LecturaSlugRoute
  '/test/$slug': typeof TestSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/perfil': typeof PerfilRoute
  '/lectura/$slug': typeof LecturaSlugRoute
  '/test/$slug': typeof TestSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/perfil' | '/lectura/$slug' | '/test/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/perfil' | '/lectura/$slug' | '/test/$slug'
  id: '__root__' | '/' | '/perfil' | '/lectura/$slug' | '/test/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PerfilRoute: typeof PerfilRoute
  LecturaSlugRoute: typeof LecturaSlugRoute
  TestSlugRoute: typeof TestSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectura/$slug': {
      id: '/lectura/$slug'
      path: '/lectura/$slug'
      fullPath: '/lectura/$slug'
      preLoaderRoute: typeof LecturaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$slug': {
      id: '/test/$slug'
      path: '/test/$slug'
      fullPath: '/test/$slug'
      preLoaderRoute: typeof TestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PerfilRoute: PerfilRoute,
  LecturaSlugRoute: LecturaSlugRoute,
  TestSlugRoute: TestSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
